[project]
name = "sklearn-pr-tracker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bokeh>=3.7.3",
    "hvplot>=0.11.3",
    "pandas>=2.3.0",
    "panel>=1.7.2",
    "requests>=2.32.4",
]
